services:

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - gateway

  # gateway
  gateway:
    build:
      context: gateway
      dockerfile: ./Dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - service-user


  # Microservice utilisateur

  service-user:
    build:
      context: service-user
      dockerfile: ./Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017/users_db
      - PORT=3001
    depends_on:
      - mongodb


  # Microservice cotes

  service-odd:
    build:
      context: service-odd
      dockerfile: ./Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017/odds_db
      - PORT=3002
    depends_on:
      - mongodb


  # Microservice paris

  service-bet:
    build:
      context: service-bet
      dockerfile: ./Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017/users_db
      - PORT=3003
    depends_on:
      - mongodb

  # Microservice paiements

  service-payment:
    build:
      context: service-payment
      dockerfile: ./Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017/payments_db
      - PORT=3005
    depends_on:
      - mongodb

  # Microservice matchs

  service-match:
      build:
        context: service-match
        dockerfile: ./Dockerfile
      environment:
        - MONGO_URI=mongodb://mongodb:27017/matches_db
        - PORT=3004
      depends_on:
        - mongodb


  # Gestion de la base de données

  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
